"""
Samudra Manthan Scheme Keywords, Entities, Company Mappings, and Event Taxonomy.
"""
from __future__ import annotations

from typing import Dict, List

SAMUDRA_KEYWORDS: List[str] = [
    "samudra manthan",
    "samudramanthan",
    "national offshore exploration scheme",
    "offshore exploration",
    "deepwater",
    "ultra-deepwater",
    "ultra deepwater",
    "oalp",
    "open acreage licensing",
    "open acreage licensing policy",
    "hydrocarbon exploration",
    "seismic survey",
    "2d seismic",
    "3d seismic",
    "national data repository",
    "ndr",
    "drilling rig",
    "drillship",
    "jackup rig",
    "jack-up rig",
    "semi-submersible",
    "kg basin",
    "kg-dwn-98/2",
    "kg-d6",
    "krishna godavari",
    "andaman basin",
    "andaman offshore",
    "mahanadi basin",
    "mahanadi offshore",
    "mumbai offshore",
    "mumbai high",
    "cambay offshore",
    "kutch offshore",
    "kerala konkan",
    "ravva offshore",
    "hydrocarbon discovery",
    "gas discovery",
    "oil discovery",
    "subsea pipeline",
    "subsea manifold",
    "floating production",
    "fpso",
    "exploratory well",
    "appraisal well",
    "exploration block",
    "revenue sharing contract",
    "disclosed discovery",
    "tender award",
    "rig charter",
    "drilling contract",
    "seismic contract",
    "well test",
    "brent crude",
    "natural gas price",
    "upstream capex",
]

SAMUDRA_ENTITIES: List[str] = [
    "Directorate General of Hydrocarbons",
    "DGH",
    "Ministry of Petroleum and Natural Gas",
    "MoPNG",
    "Prime Minister's Office",
    "PMO",
    "Oil and Natural Gas Corporation",
    "ONGC",
    "Oil India Limited",
    "OIL",
    "Reliance Industries",
    "RIL",
    "Vedanta Limited",
    "Cairn Oil & Gas",
    "Cairn India",
    "bp",
    "British Petroleum",
    "Jindal Drilling & Industries",
    "Jindal Drilling",
    "SEAMEC Limited",
    "SEAMEC",
    "Dolphin Offshore Enterprises",
    "Dolphin Offshore",
    "Aban Offshore",
]

SAMUDRA_COMPANY_MAPPINGS: Dict[str, List[str]] = {
    "Oil and Natural Gas Corporation": [
        "ongc",
        "oil and natural gas corporation",
        "oil and natural gas corp",
        "oil & natural gas corporation",
        "kg-dwn-98/2",
        "mumbai high",
    ],
    "Oil India Limited": [
        "oil india",
        "oil india limited",
        "oil india ltd",
        "oil",
    ],
    "Reliance Industries": [
        "reliance",
        "reliance industries",
        "reliance industries limited",
        "ril",
        "kg-d6",
        "reliance gas",
    ],
    "Vedanta Limited": [
        "vedanta",
        "vedanta limited",
        "vedl",
        "cairn",
        "cairn oil & gas",
        "cairn india",
        "ravva",
    ],
    "Jindal Drilling & Industries": [
        "jindal drilling",
        "jindal drilling & industries",
        "jindcot",
    ],
    "SEAMEC Limited": [
        "seamec",
        "seamec limited",
        "seamec ltd",
    ],
    "Dolphin Offshore Enterprises": [
        "dolphin offshore",
        "dolphin offshore enterprises",
    ],
    "Aban Offshore": [
        "aban offshore",
        "aban",
    ],
}

SAMUDRA_EVENT_TAXONOMY: List[str] = [
    "SCHEME_POLICY",
    "OFFSHORE_EXPLORATION",
    "DEEPWATER",
    "ULTRA_DEEPWATER",
    "OALP",
    "BLOCK",
    "SEISMIC",
    "DRILLING",
    "DISCOVERY",
    "PRODUCTION",
    "TENDER",
    "CONTRACT",
    "CAPEX",
    "INFRASTRUCTURE",
    "EQUIPMENT",
    "SERVICES",
    "REGULATORY",
    "PARTNERSHIP",
    "JV",
    "PROJECT_DELAY",
    "DRY_WELL",
    "COST_RISK",
    "COMMODITY_RISK",
    "MARKET_IMPACT",
]

COMPANY_KEYWORDS = SAMUDRA_COMPANY_MAPPINGS
