"""
Samudra Manthan / National Offshore Exploration Scheme Official Information Sources.
Includes regulatory bodies (DGH), ministry feeds (MoPNG, PIB, PMO),
procurement portals (CPPP), operator disclosures (ONGC, OIL, RIL, VEDL), and exchange filings (NSE, BSE).
"""
from __future__ import annotations

from typing import List
from ..models import SchemeSource

SAMUDRA_SOURCES: List[SchemeSource] = [
    SchemeSource(
        id="dgh_portal",
        name="Directorate General of Hydrocarbons (DGH)",
        type="html",
        url="https://dghindia.gov.in",
        tier=1,
        enabled=True,
        poll_interval_hours=4,
        categories=["oalp", "exploration", "deepwater", "acreage", "bidding", "disclosures"],
        trust_level=1,
        refresh_frequency="4h",
        parser="dgh_html",
    ),
    SchemeSource(
        id="pib_mopng_samudra",
        name="PIB Ministry of Petroleum & Natural Gas",
        type="rss",
        url="https://pib.gov.in/RssMain.aspx?ModId=2&MinId=30",
        tier=1,
        enabled=True,
        poll_interval_hours=2,
        categories=["policy", "offshore", "exploration", "samudra_manthan", "e&p"],
        trust_level=1,
        refresh_frequency="2h",
        parser="pib_rss",
    ),
    SchemeSource(
        id="pib_national_energy",
        name="PIB National Energy & Infrastructure",
        type="rss",
        url="https://pib.gov.in/RssMain.aspx?ModId=6&Lang=1&Regid=3",
        tier=1,
        enabled=True,
        poll_interval_hours=3,
        categories=["cabinet", "policy", "energy", "infrastructure"],
        trust_level=1,
        refresh_frequency="3h",
        parser="pib_rss",
    ),
    SchemeSource(
        id="pmo_releases",
        name="Prime Minister's Office Press Releases",
        type="html",
        url="https://www.pmindia.gov.in/en/news-updates/",
        tier=1,
        enabled=True,
        poll_interval_hours=6,
        categories=["cabinet_decisions", "strategic_initiatives", "energy_security"],
        trust_level=1,
        refresh_frequency="6h",
        parser="pmo_html",
    ),
    SchemeSource(
        id="cppp_hydrocarbons",
        name="Government eProcurement - Hydrocarbon & Offshore Tenders",
        type="tender",
        url="https://eprocure.gov.in/cppp/",
        tier=2,
        enabled=True,
        poll_interval_hours=4,
        categories=["drilling_tenders", "seismic_tenders", "rig_charters", "subsea_epc"],
        trust_level=2,
        refresh_frequency="4h",
        parser="cppp_tender",
    ),
    SchemeSource(
        id="ongc_corporate",
        name="ONGC Corporate & Offshore Project Disclosures",
        type="html",
        url="https://ongcindia.com/web/eng/media/press-releases",
        tier=1,
        enabled=True,
        poll_interval_hours=3,
        categories=["offshore_projects", "kg_basin", "drilling_awards", "production_updates"],
        trust_level=1,
        refresh_frequency="3h",
        parser="ongc_html",
    ),
    SchemeSource(
        id="oil_india_corporate",
        name="Oil India Corporate Press Releases",
        type="html",
        url="https://www.oil-india.com/PressReleases",
        tier=1,
        enabled=True,
        poll_interval_hours=3,
        categories=["offshore_blocks", "andaman_exploration", "oalp_awards"],
        trust_level=1,
        refresh_frequency="3h",
        parser="oil_india_html",
    ),
    SchemeSource(
        id="ril_investor_updates",
        name="Reliance Industries Investor Disclosures",
        type="html",
        url="https://www.ril.com/investor-relations",
        tier=1,
        enabled=True,
        poll_interval_hours=4,
        categories=["kg_d6", "deepwater_gas", "upstream_production"],
        trust_level=1,
        refresh_frequency="4h",
        parser="ril_html",
    ),
    SchemeSource(
        id="vedanta_corporate",
        name="Vedanta / Cairn Oil & Gas Corporate Disclosures",
        type="html",
        url="https://www.vedantalimited.com/investor-relations",
        tier=1,
        enabled=True,
        poll_interval_hours=4,
        categories=["cairn", "ravva", "oalp_acreage"],
        trust_level=1,
        refresh_frequency="4h",
        parser="vedanta_html",
    ),
    SchemeSource(
        id="nse_energy_filings",
        name="NSE Corporate Filings (Energy & Upstream)",
        type="filing",
        url="https://www.nseindia.com/companies-listing/corporate-filings-announcements?tabIndex=equity",
        tier=2,
        enabled=True,
        poll_interval_hours=2,
        categories=["contract_awards", "joint_ventures", "material_disclosures"],
        trust_level=2,
        refresh_frequency="2h",
        parser="exchange_filing",
    ),
    SchemeSource(
        id="bse_energy_announcements",
        name="BSE Corporate Announcements (Energy & Upstream)",
        type="filing",
        url="https://www.bseindia.com/corporates/ann.html",
        tier=2,
        enabled=True,
        poll_interval_hours=2,
        categories=["board_meetings", "tender_wins", "financial_results"],
        trust_level=2,
        refresh_frequency="2h",
        parser="exchange_filing",
    ),
]

SOURCES = SAMUDRA_SOURCES
